spring:
  application:
    name: person
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      legacy_limit_handler: true
  jmx:
    enable: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: docker
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: D:/projeto/Udemy/calculadora-rest/upload


flyway:
  url: jdbc:mysql://db:3306/
  schemas: rest_with_spring_boot_udemy
  user: root
  password: docker